### ISSUE TITLE
Missing input in cell identification

### ISSUE THREAD

**Issue by Elzi7** [DrHanLim/EzColocalization#11]
Hi, I'd like to ask for help as I've not been successful even though I've tried doing colocalisation analysis with my stacks using Ezcolocalisation. I've opened the files by going files>open then choosing my two tiff images (1024x1024); 16-bit;158MB which are the same, however, each represents the green and the red channels, respectively, that I'd split and saved beforehand. In "inputs" Ideally I wouldn't need to ROI it, however, if I don't, I'm really unsure what to put in "Cell identification input''. So now I've tried ROIng it however, if I do, the following appears:
![20210106_120028](https://user-images.githubusercontent.com/77053487/103767949-773fb380-5019-11eb-9aa1-a8c31a907036.jpg)

Any help would be much appreciated!

Many thanks.

Kind Regards,
Elzi

**Comment by shenghuanjie** [comment]
Hi, @Elzi7 Please use ROI manager and add your selection to the ROI manager before using it to identify your cell.
You can find the ROI manager here. Click add to add your selection to the ROI manager before running your analysis
![image](https://user-images.githubusercontent.com/25040735/104146324-2a444000-537f-11eb-9bfa-a276f4bdec76.png)
I also notice that you might want to apply the same ROI to all slices in your stack. You can find the option in EzColocalization parameters from below: (Click Parameters.. a popup window will show, choose the last option)
![image](https://user-images.githubusercontent.com/25040735/104146411-74c5bc80-537f-11eb-9282-67302a4206c1.png)
![image](https://user-images.githubusercontent.com/25040735/104146423-7db68e00-537f-11eb-9932-62599efe8e71.png)

**Comment by shenghuanjie** [comment]
@westonstauffer Anything you want to add?

**Comment by westonstauffer** [comment]
I would add that if @Elzi7 would ideally like to not use an ROI to identify cell area, a couple other simple options exist. When not selecting any cell id input, the entire image is analyzed which is ideal if you have a cell in the whole field of view. You could also duplicate one of your channels that marks the entire cell area and use a manual or algorithm threshold to select the cell area(s).

**Comment by Elzi7** [comment]
Hi again,

Many thanks to both of you! Your advice has proven most helpful over the
last few weeks.


Kind Regards,

**Comment by shenghuanjie** [comment]
It seems like the issue has been resolved. I will go ahead and close this issue.
