### ISSUE TITLE
ROI manager malfunction

### ISSUE THREAD

**Issue by lauraczd** [DrHanLim/EzColocalization#5]
Dear authors,

sorry to disturb but I have been using the last version of EZColocalisation to analise stacks of pre-aligned SIM data in the last few days and I am having trouble using the ROI selection function.

I select the ROIs manually, add them to the ROI manager as normal (and as indicated in your Sci Rep 2018 paper), and then select ROI manager as cell idenitication input image and *Manual* as cell identification input method in the box below the alignment method. Finally I click the ROI checkbox in the Analysis tab as method for cell identification function.

This invariably causes the analysis to fall over with the error log below.
******************Errors******************
(ezcol.cell.CellDataProcessor.mask2data(CellDataProcessor.java:84)): No cell is found based on the selected filters.
(ezcol.main.AnalysisOperator.applyToStack(AnalysisOperator.java:420)): Error in cell data processor on slice 1
(ezcol.main.AnalysisOperator.applyToStack(AnalysisOperator.java:469)): Error in calculating metrics on slice 1
(ezcol.main.AnalysisOperator.applyToStack(AnalysisOperator.java:476)): Error in calculating mTOS on slice 1
(ezcol.main.AnalysisOperator.finishStack(AnalysisOperator.java:576)): No result to be printed
ezcol.main.AnalysisOperator(ezcol.main.AnalysisOperator.finishStack(AnalysisOperator.java:801)): Output ResultsTable is empty

END ERROR LOG

Initially I though it might have been an issue of the stacks being too big and my machine being too weak to handle the dataset (even though it has 16GB of memory and an Intel i7 8th gen processor), however I have managed to replicate the same problem also with single 16-bit .tiff images extracted from the stack, as long as more than 3 non-overlapping areas are selected.
This goes contrary to what shown in the Sci Rep 2018 paper, in figures 7 and 8, where the workflow is implied to work with >3 ROIs.

Could you please look into this and, if this is a matter of machine requisites, could you please indicate what are the minimal requisites necessary for a 2-colour colocalisation workflow using ROI on pre-aligned 16-bit .tiff stacks?

Regards,

Laura C Zanetti Domingues

**Comment by lauraczd** [comment]
Dear authors,

I found another error when using the ROI manager. I selected two ROIs (marked 1 and 2 on the screenshot) and run the plugin with the parameters indicated in the screenshot, and the EzColocalisation plugin actually analysed the tiny area marked on the green cells on the right of the screenshot, which is between the two areas I asked it to analyse.

This might have happened because watershed segmentation was accidentally selected in the filters tab, even though I have no idea why it would have selected a third area at the boundary of the selected two (which were non-overlapping).

Best,

Laura C Zanetti Domingues
![EzColocalisationError_ROImanager-Subtract](https://user-images.githubusercontent.com/26622855/65260509-5f7bad80-dafe-11e9-8964-01c950b0d5c7.png)

**Comment by shenghuanjie** [comment]
@Sereq Hi Laura, sorry for the late response. Thank you for reaching out and reporting the issue you encountered. We are investigating this problem.
Can you attach your sample images and the selected ROIs or send it to shenghuanjie@berkeley.edu?
You can save your ROIs within the ROImanger at More>>Save. Make sure you deselect or select all ROIs so they are saved together as a zip file. In addition, it would be very helpful if you could share your settings on the other tabs as well.
We will try to fix or advice on this issue ASAP.

**Comment by westonstauffer** [comment]
@Sereq Hi Laura, 

Thank you for letting us know about your issues, and we are happy to help! For your first issue, we were able to recreate it and found that it occurred when cell filters were removing all cells from analysis. Can you confirm that you aren’t using a cell filter (on the “Cell Filters” tab) which is too narrow to select any of your ROIs? In other words, have you entered any ranges within that panel, which may exclude your ROIs?

For your second issue, we weren’t able to recreate a similar result. Would you be willing to share the example images you gave, along with inputs across all tabs so we can work on amending it? If you are willing, you can email them to myself (westonstauffer@berkeley.edu), or to shenghuanjie@berkeley.edu. Please let us know if the first fix works for you too.

Sincerely,
Weston

**Comment by lauraczd** [comment]
Hi folks,

thanks for replying. I have had another instance of no cells being found even with ROI selected and no filters selected. I am attaching all material, so you can have a check.
I suspect it didn't handle the large area that well, because when I reduced it to two cells worth instead of three, it worked fine.
All cell filters are left as default, 0-Infinite, so there is no way they can be rejecting my admittedly crappy cells.
I will email you the ROI file, as it's not letting me attach it. T_T

I will try to replicate the other issue, but TBH I think it was a bug caused by having accidentally selected watershed filtering in the cell filter tab. All other options in that tab were left as default, like I always do.

Best,

Laura

![Errortest1](https://user-images.githubusercontent.com/26622855/65700914-5a77aa80-e078-11e9-8346-ac71d5f20685.png)
![Errortest2](https://user-images.githubusercontent.com/26622855/65700916-5a77aa80-e078-11e9-8f4f-846f5d969471.png)
![Cbl_test](https://user-images.githubusercontent.com/26622855/65700945-69f6f380-e078-11e9-97e3-ac4cfd573f0d.png)
![EGFR_test](https://user-images.githubusercontent.com/26622855/65700947-69f6f380-e078-11e9-8b4f-7f88873e5596.png)
[EzColocalization  errors_20190926.txt](https://github.com/DrHanLim/EzColocalization/files/3658493/EzColocalization.errors_20190926.txt)

**Comment by shenghuanjie** [comment]
@Sereq Thank you for your feedback. You are right, EzColocalization is not optimized for very large images/objects.  We are considering pushing a major update soon given that images are getting larger and larger very fast.  A temporary solution is to use the provided Macro function to run

**Comment by shenghuanjie** [comment]
@Sereq I'm able to reproduce the error you mentioned. Sorry for the inconvenience brought by this issue. It was introduced in 1.1.0. 
By default, EzColocalization tries to automatically determine the background versus the objects.
In your case, your object is bigger than the background so EzColocalization thought your object was the background.
We will try to fix it. 
As a temporary work-around for now, you can go to the EzColocalization menu.
Settings -> Parameters 
Check ONLY the following box:
Use Manual Background Settings Below.
It should do the job.
In the future release, we will not try to automatically identify background versus foreground if ROI manager is used.

On the other hand, I don't understand your issue about the watershed option.

**Comment by shenghuanjie** [comment]
This issue has been fixed in 1.1.3
EzColocalization will NOT attempt to automatically detect light/dark background in the cell identification channel if ROI manager is used.

**Comment by lauraczd** [comment]
Dear Dr Lim,

Thanks a lot for the fix. I will update the software on Monday.

Have a lovely weekend,

Laura C Zanetti Domingues

Il Sab 5 Ott 2019 02:36 Huanjie Sheng <notifications@github.com> ha scritto:

**Comment by shenghuanjie** [comment]
@Sereq I just pushed the update to ImageJ update site and drafted a new release in this github repository.
You can choose either way to update the plugin.
Please let us know if any other issue develops and we are always happy to help.
I will go ahead and close this issue.

**Comment by Aqsa2424** [comment]
Hi,

I am having all of these errors while doing localization analysis. Can you please tell me what I can do?

******************Errors******************
(ezcol.main.AnalysisOperator.finishStack(AnalysisOperator.java:581)): No result to be printed
ezcol.main.AnalysisOperator(ezcol.main.AnalysisOperator.finishStack(AnalysisOperator.java:807)): Output ResultsTable is empty
******************Warnings******************
(ezcol.cell.CellDataProcessor.mask2data(CellDataProcessor.java:84)): No cell is found based on the selected filters on some slices.
Apply ROIs to all slices in Settings->Parameters->Apply ROIs to all slices.
(ezcol.main.AnalysisOperator.applyToStack(AnalysisOperator.java:421)): No cell can be found in cell data processor on slice 1
