### ISSUE TITLE
Time-lapse incompatibility with ROIs and ROI errors

### ISSUE THREAD

**Issue by westonstauffer** [DrHanLim/EzColocalization#6]
We have found that time-lapse images stored in a series of frames, instead of a z-stack are not compatible with analysis when an ROI manager is used as cell identification. Trying to perform analysis with this combination leads to an error or inability of the plugin to run. An immediate workaround is to convert a series of "frames" into a series of "slices" (a z-stack), but an update will be released shortly which fixes this incompatibility. To convert frames to slices, open a time series of images, and then select "Image"->"Stacks"->"Stacks to Images" from the menu bar. Next, select "Image"->"Stacks"->"Images to Stacks", and save the produced stack. Repeat this for every channel to be analyzed and the time series of images can now be used with ROIs.

In a separate issue, if any slice in a z-stack has no ROIs for analysis and the ROI manager is used for cell selection, non-critical errors are reported, as no analysis can be performed for that slice. This is a non-critical error in that analysis will run correctly for other images in the stack. These errors will be preceded by the warning: "No cell is found based on the selected filters in some slices." within the error window in a new EzColocalization version released in the near future.

**Comment by shenghuanjie** [comment]
This bug is fixed in 1.1.3.
