### ISSUE TITLE
Import .csv for reprocessing?

### ISSUE THREAD

**Issue by wolf5464** [DrHanLim/EzColocalization#7]
Hi authors,

Is it possible to import generated .csv files back into ImageJ to generate heat maps after the initial Ez Colocalisation analysis? I'm hoping to compile data from multiple images into a single .csv file, re-run colocalisation analysis and generate a collated heat map.

Kind regards,
Scott.

**Comment by westonstauffer** [comment]
This is not a functionality within the plugin, but your collated heat maps can be produced using a workflow within ImageJ. 
First, you will need to combine your images into a z-stack. This can be done by opening the images in ImageJ and then selecting "Image"->"Stacks"->"Images to Stacks" from the menu bar of ImageJ. Next, create a sum projection of your images, which adds all pixel values for any given coordinate within a z-stack. This can be done by selecting "Image"->"Stacks"->"Z-project...", then select "Sum Slices" from the drop down menu within the dialog box which opens, and finally click "OK". This created image is a collated image, and can be used within EzColocalization to create a heat map.

**Comment by westonstauffer** [comment]
closed #7

**Comment by westonstauffer** [comment]
Closed #7

**Comment by westonstauffer** [comment]
Closes: #7

**Comment by shenghuanjie** [comment]
@wolf5464 Please let us know if the comment above resolves your issue.

**Comment by shenghuanjie** [comment]
Close this due to inactivity.
